---
title: "Tools for tree point clouds"
author: "Yuwei Cao"
date: "2025-04-01"
date-modified: "2025-04-01"
categories: [data]
draft: true
---

# Data management
| Name | author/institution | language | description | 
|---------|:-----|------:|:------:|
| [pytreedb](https://pytreedb.geog.uni-heidelberg.de)       | 3DGeo Research Group of Heidelberg University and the Institute of Geography and Geoecology (IFGG) of Karlsruhe Institute of Technology (KIT).    |    python + REST |   pytreedb is a file- and object-based database for managing laser scanning and inventory data of single trees.   | 

: Tools for Lidar Point Cloud Management

- [pytreedb](https://pytreedb.geog.uni-heidelberg.de)  
  - manage data: Trees are imported from GeoJSON files which contain information on tree location, species, and tree properties, and link to one or multiple point clouds. These single tree 3D datasets may be extracted from airborne, UAV-borne or terrestrial laser scanning data.
  - pytreedb allows filtering the data, e.g., by location, tree properties, linked data types or acquisition dates. 
  - The database may be used to populate synthetic forest stands of given species composition and stand density for laser scanning simulations or radiative transfer models. 

# Data processing

